import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const displayFont = Space_Grotesk({
  variable: "--font-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${displayFont.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <nav className="border-b-4 border-ink bg-butter">
          <div className="mx-auto flex w-full max-w-6xl items-center justify-between gap-4 px-5 py-4 lg:px-8">
            <Link
              href="/"
              className="font-display text-xl font-black tracking-tight text-ink hover:underline"
            >
              BLOG//LAB
            </Link>
            <div className="hidden items-center gap-5 font-display text-sm font-bold text-ink sm:flex">
              <Link href="/" className="hover:underline">
                Artikel
              </Link>
              <Link href="/dashboard" className="hover:underline">
                Dashboard
              </Link>
            </div>
            <Link
              href="/login"
              className="border-3 border-ink bg-white px-4 py-2 font-display text-sm font-bold text-ink shadow-brutal-sm transition-[transform,box-shadow,background-color] duration-150 hover:translate-x-0.5 hover:translate-y-0.5 hover:bg-mint hover:shadow-none"
            >
              Login
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
